# Generated by Django 3.1 on 2023-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=70)),
                ('stemail', models.CharField(max_length=70)),
                ('stpass', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=70)),
            ],
        ),
    ]
